In [1]:
import sys
import os

sys.path.append(os.getcwd())
sys.path.append(f"{os.getcwd()}/..")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize
from matplotlib.patches import Rectangle

import modeling
import wifiplotting as wp
from wifiplotting import TL_CORNER, BR_CORNER

In [2]:
sequoia_df = pd.read_csv("../../data/sequoia.csv", index_col="index", converters={"timestamp": pd.to_datetime}).reset_index(drop=True)

In [3]:
sequoia_df.head()

,date,time_pdt,latitude,longitude,indoor,ap,floor,rssi_set,rssi_sample,rssi_signal_measured,rssi_n_valid,noise_set,noise_sample,noise_n_valid,noise_signal_measured,timestamp,location_timestamp,mid
0,2026-04-27,17:11:02.508330,37.428992,-122.171906,True,a8:3a:79:c7:75:12,1,-45.000000,-45.0,True,3,-97.0,-97.0,3,True,2026-04-27 17:11:02.508330-07:00,2026-04-28 00:11:04+00:00,07d6fa75def0
1,2026-04-27,17:11:03.719977,37.428992,-122.171906,True,a8:3a:79:c7:75:12,1,-45.000000,-45.0,True,3,-97.0,-97.0,3,True,2026-04-27 17:11:03.719977-07:00,2026-04-28 00:11:04+00:00,07d6fa75def0
2,2026-04-27,17:11:04.951550,37.428992,-122.171906,True,a8:3a:79:c7:75:12,1,-45.000000,-45.0,True,3,-97.0,-97.0,3,True,2026-04-27 17:11:04.951550-07:00,2026-04-28 00:11:04+00:00,07d6fa75def0
3,2026-04-27,17:11:07.470753,37.428992,-122.171906,True,a8:3a:79:c7:75:12,1,-44.333333,-45.0,True,3,-97.0,-97.0,3,True,2026-04-27 17:11:07.470753-07:00,2026-04-28 00:11:09+00:00,825d2cb1e35a
4,2026-04-27,17:11:08.676819,37.428992,-122.171906,True,a8:3a:79:c7:75:12,1,-44.333333,-44.0,True,3,-97.0,-97.0,3,True,2026-04-27 17:11:08.676819-07:00,2026-04-28 00:11:09+00:00,825d2cb1e35a

In [4]:
sequoia_df_sets = sequoia_df.groupby("mid").agg(
    {
        "time_pdt": "first",
        "timestamp": "first",
        "latitude": "first",
        "longitude": "first",
        "indoor": "first",
        "ap": "first",
        "rssi_set": "first",
        "rssi_n_valid": "first",
        "noise_set": "first",
        "noise_n_valid": "first",
    }
)

In [5]:
sequoia_df_sets.to_csv(
    "../../data/sequoia_sets.csv"
)

In [6]:
sequoia_df_sets.shape

(2703, 10)

In [7]:
from modeling import binned_group_mean

In [8]:
sequoia_df['timestamp_rd'] = sequoia_df['timestamp'].dt.floor("1min")

In [ ]:
# binned_group_mean(
#     sequoia_df,
#     lat_bins=100,
#     lon_bins=100,
#     extra_groups=['timestamp_rd']
# )

,indoor,lat_bin,lon_bin,lat_bounds,lon_bounds,timestamp_rd,mean,var,n_obs
0,False,0,83,"(37.42705202003412, 37.427087314076815)","(-122.17017922037675, -122.17013442498795)",2026-05-11 17:26:00-07:00,-73.500000,4.500000,2
1,False,0,84,"(37.42705202003412, 37.427087314076815)","(-122.17013442498795, -122.17008962959915)",2026-05-11 17:26:00-07:00,-79.000000,1.000000,3
2,False,0,85,"(37.42705202003412, 37.427087314076815)","(-122.17008962959915, -122.17004483421033)",2026-05-11 17:26:00-07:00,-80.000000,28.666667,4
3,False,0,89,"(37.42705202003412, 37.427087314076815)","(-122.16991044804391, -122.16986565265509)",2026-05-11 17:27:00-07:00,-71.666667,574.333333,3
4,False,0,90,"(37.42705202003412, 37.427087314076815)","(-122.16986565265509, -122.16982085726629)",2026-05-11 17:27:00-07:00,-85.333333,0.333333,3
...,...,...,...,...,...,...,...,...,...
1970,True,98,52,"(37.43051083621857, 37.43054613026128)","(-122.17156787742984, -122.17152308204103)",2026-05-08 15:31:00-07:00,-66.000000,4.333333,7
1971,True,98,52,"(37.43051083621857, 37.43054613026128)","(-122.17156787742984, -122.17152308204103)",2026-05-08 15:32:00-07:00,-71.625000,22.553571,8
1972,True,99,51,"(37.43054613026128, 37.43058142430397)","(-122.17161267281865, -122.17156787742984)",2026-05-08 15:32:00-07:00,-58.333333,0.333333,3
1973,True,99,54,"(37.43054613026128, 37.43058142430397)","(-122.17147828665222, -122.17143349126341)",2026-05-08 15:35:00-07:00,-60.500000,6.055556,10
1974,True,99,55,"(37.43054613026128, 37.43058142430397)","(-122.17143349126341, -122.1713886958746)",2026-05-08 15:31:00-07:00,-58.000000,NaN,1